const Images = {
  'Luke Skywalker': '../images/Luke.png',
  "C-3PO":'../images/C3PO.png',
  "R2-D2": '../images/R2D2.png',
  'Bespin': '../images/bespin.png',
  'Alderaan': '../images/alderaan.jpg',
  'Coruscant': '../images/coruscant.png',
  'Dagobah': '../images/dagobah.jpg',
  'Endor': '../images/endor.jpg',
  'Geonosis': '../images/geonosis.jpg',
  'Hoth': '../images/hoth.png',
  'Kamino': '../images/kamino.jpg',
  'Naboo': '../images/naboo.png',
  'Yavin IV': '../images/bespin.png',
  "Darth Vader": '../images/vader.png',
  "Leia Organa": '../images/leia.png',
  "Owen Lars": '../images/owen.png',
  "Beru Whitesun lars": '../images/beru.png',
  "R5-D4": '../images/r5d4.png',
  "Biggs Darklighter": '../images/biggs.png',
  "Obi-Wan Kenobi": '../images/obiwan.png',
  "Sand Crawler": '../images/sandcrawler.png',
  "T-16 skyhopper": '../images/skyhopper.png',
  "X-34 landspeeder": '../images/landspeeder.png',
  "TIE/LN starfighter": '../images/starfighter.png',
  "Snowspeeder": '../images/snowspeeder.png',
  "TIE bomber": '../images/bomber.png',
  "AT-AT": '../images/atat.png',
  "AT-ST": '../images/atst.png',
  "Storm IV Twin-Pod cloud car": '../images/storm.png',
  "Sail barge": '../images/sail.png',
  "white-saber": '../images/white-lightsaber.svg',
  'green-saber': '../images/green-lightsaber.svg'
}

export default Images;