const Side = {
  'Luke Skywalker': 'light',
  "C-3PO":'light',
  "R2-D2": 'light',
  'Bespin': 'light',
  'Alderaan': 'light',
  'Coruscant': 'dark',
  'Dagobah': 'light',
  'Endor': 'light',
  'Geonosis': 'dark',
  'Hoth': 'dark',
  'Kamino': 'dark',
  'Naboo': 'light',
  'Yavin IV': 'dark',
  "Darth Vader": 'dark',
  "Leia Organa": 'light',
  "Owen Lars": 'light',
  "Beru Whitesun lars": 'light',
  "R5-D4": 'light',
  "Biggs Darklighter": 'light',
  "Obi-Wan Kenobi": 'light',
  "Sand Crawler": 'dark',
  "T-16 skyhopper": 'dark',
  "X-34 landspeeder": 'light',
  "TIE/LN starfighter": 'dark',
  "Snowspeeder": 'light',
  "TIE bomber": 'dark',
  "AT-AT": 'dark',
  "AT-ST": 'dark',
  "Storm IV Twin-Pod cloud car": 'light',
  "Sail barge": 'dark'
}

export default Side